project:
  type: book

book:
  title: "Ovarian Cancer Histotypes: Report of Statistical Findings"
  author: "Derek Chiu"
  description: "This report of statistical findings summarizes results for the classification of ovarian cancer histotypes."
  date: today
  date-format: long
  chapters:
    - index.qmd
    - rsf/introduction.qmd
    - rsf/methods.qmd
    - rsf/distributions.qmd
    - rsf/results.qmd
    - rsf/references.qmd
  repo-url: https://github.com/TalhoukLab/OV_Histotypes
  repo-actions: [edit, issue]
  downloads: pdf
  reader-mode: true

bibliography: book.bib

crossref:
  chapters: true

format:
  html:
    theme:
      - cosmo
    html-table-processing: none
    fig-dpi: 300
  pdf:
    documentclass: scrreprt
    geometry: margin=1in
    colorlinks: true
    lof: true
    lot: true
    biblio-style: apalike
    link-citations: true
    keep-tex: true
    fig-pos: H
    fig-align: center
    fig-dpi: 300
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
        \floatplacement{table}{H}

execute:
  echo: false
  message: false
  warning: false
  freeze: auto

editor: visual
