# Distributions

```{r setup-03}
library(Amisc)
library(batchAdj)
library(forcats)
library(scales)
library(patchwork)
library(here)
source(here("validation/cs_classifier.R"))
```

## Histotypes in Classifier Data

```{r preqc-hist-codeset}
cs1_samples_preqc <- cohorts %>%
  filter(
    file_source == "cs1",
    cohort %in% c("MAYO", "OOU", "OOUE", "VOA", "MTL")
  ) %>%
  pull(col_name)

cs2_samples_preqc <- cohorts %>%
  filter(
    file_source == "cs2",
    cohort %in% c("MAYO", "OOU", "OOUE", "OVAR3", "VOA", "ICON7", "JAPAN", "MTL", "POOL-CTRL"),
  ) %>%
  pull(col_name)

cs3_samples_preqc <- cohorts %>%
  filter(
    file_source == "cs3",
    cohort %in% c("DOVE4", "OOU", "OOUE", "TNCO", "VOA", "POOL-1", "POOL-2", "POOL-3"),
    !cohort %in% c("TNCO", "DOVE4"),
    !grepl("pool", col_name, ignore.case = TRUE)
  ) %>%
  pull(col_name)

preqc_df <-
  list(list(cs1, cs2, cs3),
       list(cs1_samples_preqc, cs2_samples_preqc, cs3_samples_preqc)) %>%
  pmap( ~ {
    ..1 %>%
      dplyr::select(Name, all_of(..2)) %>%
      column_to_rownames("Name") %>%
      t() %>%
      as.data.frame() %>%
      select(all_of(common_genes123))
  }) %>% 
  bind_rows() %>%
  rownames_to_column("FileName") %>%
  mutate(FileName = gsub("^X", "", FileName)) %>% 
  inner_join(hist, by = "FileName") %>%
  filter(revHist %in% c("CCOC", "ENOC", "HGSC", "LGSC", "MUC")) %>%
  column_to_rownames("FileName")

preqc_hist_codeset <- preqc_df %>% 
  mutate(revHist = fct_infreq(revHist)) %>% 
  describeBy(
    var.names = "revHist",
    var.labels = "Histotype",
    by1 = "CodeSet",
    test = FALSE,
    total = "bottom",
    bold_var = FALSE
  )

knitr::kable(preqc_hist_codeset,
             caption = "Pre-QC Training Set Histotype Distribution by CodeSet")
```

```{r train-all-hist-codeset}
train_all_hist_codeset <- train_ref_all %>% 
  mutate(revHist = fct_infreq(revHist)) %>% 
  describeBy(
    var.names = "revHist",
    var.labels = "Histotype",
    by1 = "CodeSet",
    test = FALSE,
    total = "bottom",
    bold_var = FALSE
  )

knitr::kable(train_all_hist_codeset,
             caption = "Training Set (with duplicates) Histotype Distribution by CodeSet")
```

```{r train-hist-codeset}
train_hist_codeset <- train_ref %>% 
  mutate(revHist = fct_infreq(revHist)) %>% 
  describeBy(
    var.names = "revHist",
    var.labels = "Histotype",
    by1 = "CodeSet",
    test = FALSE,
    total = "bottom",
    bold_var = FALSE
  )

knitr::kable(train_hist_codeset,
             caption = "Final Training Set Histotype Distribution by CodeSet")
```

```{r hist-conf-val}
hist_conf_val <- list(Confirmation = conf_ref,
                      Validation = val_ref) %>% 
  map_dfr(~ select(., revHist), .id = "Data") %>%
  mutate(Data = factor(Data, levels = c("Confirmation", "Validation")),
         revHist = factor(revHist, levels = c("HGSC", "CCOC", "ENOC", "MUC", "LGSC"))) %>%
  describeBy(
    var.names = "revHist",
    var.labels = "Histotype",
    by1 = "Data",
    total = "bottom",
    test = FALSE,
    bold_var = FALSE
  ) %>% 
  select(-Total)

knitr::kable(hist_conf_val,
             caption = "Histotype Distribution in Confirmation and Validation Sets")
```

## Cohorts in Classifier Data

```{r cohort-dist}
cohort_dist <- list(Training = train_ref,
                    Confirmation = conf_ref,
                    Validation = val_ref) %>%
  map(~ count(.x, CodeSet, cohort)) %>%
  list_rbind(names_to = "Data") %>%
  rename(Cohort = cohort) %>% 
  pivot_wider(
    names_from = "Data",
    values_from = "n",
    values_fill = list(n = 0)
  )

knitr::kable(cohort_dist,
             caption = "Cohort Distribution in Training, Confirmation, and Validation Sets")
```

## Quality Control

### Failed Samples

```{r qc-failed}
qc_failed <- list(CS1 = cs1_qc_failed,
                  CS2 = cs2_qc_failed,
                  CS3 = cs1_qc_failed) %>% 
  map_df(length)

qc_failed %>% 
  kable(caption = "Number of failed sampled by CodeSet")
```


### %GD vs. SNR

```{r qc-gd-snr-all, fig.height=8, fig.cap='% Genes Detected vs. Signal to Noise Ratio'}
p1 <- ggplot(cs1_qc, aes(sn, pergd)) + 
  geom_point() +
  labs(title = "CS1")
p2 <- ggplot(cs2_qc, aes(sn, pergd)) + 
  geom_point() +
  labs(title = "CS2")
p3 <- ggplot(cs3_qc, aes(sn, pergd)) + 
  geom_point() +
  labs(title = "CS3")

p_gd_snr_all <- p1 / p2 / p3 &
  labs(x = "SNR", y = "% GD") &
  geom_vline(xintercept = 100, color = "red", linetype = "dashed") &
  geom_hline(yintercept = 50, color = "red", linetype = "dashed") &
  plot_annotation(title = "% Genes Detected vs. SNR",
                  tag_levels = "a")
print(p_gd_snr_all)
```

```{r qc-gd-snr-zoomed, fig.height=8, fig.cap='% Genes Detected vs. Signal to Noise Ratio (Zoomed)'}
p_gd_snr_zoomed <- p_gd_snr_all &
  lims(x = c(0, 2000)) &
    plot_annotation(title = "% Genes Detected vs. SNR (Zoomed)",
                  tag_levels = "a")
print(p_gd_snr_zoomed)
```

## Pairwise Gene Expression

```{r genes-cs13-rand1, fig.height=10, fig.width=11, fig.cap='Random1-Normalized CS1 vs. CS3 Gene Expression'}
genes_cs13_rand1 <- train_ref_all %>%
  rownames_to_column("FileName") %>%
  group_by(ottaID) %>%
  mutate(n_codeset = n_distinct(CodeSet)) %>%
  filter(all(c("CS1", "CS3") %in% CodeSet)) %>%
  group_by(ottaID, CodeSet) %>%
  filter(n_codeset > 1, !duplicated(ottaID)) %>%
  ungroup() %>%
  pivot_longer(
    cols = where(is.double),
    names_to = "Gene",
    names_ptypes = list(Gene = factor()),
    values_to = "Value"
  ) %>%
  pivot_wider(
    id_cols = c(ottaID, Gene),
    names_from = "CodeSet",
    values_from = c("Value", "FileName")
  ) %>%
  group_by(Gene) %>%
  mutate(Rc = epiR::epi.ccc(Value_CS1, Value_CS3)[["rho.c"]][["est"]]) %>%
  ungroup() %>%
  mutate(Gene = fct_reorder(Gene, Rc, .desc = TRUE),
         Rc = paste0("Rc = ", round(Rc, digits = 3)))

p_genes_cs13_rand1 <-
  ggplot(genes_cs13_rand1, aes(x = Value_CS1, y = Value_CS3)) +
  geom_point() +
  geom_text(
    x = -24,
    y = 5,
    hjust = 0,
    vjust = 1,
    aes(label = Rc),
    check_overlap = TRUE
  ) +
  geom_abline(slope = 1,
              linetype = "dashed",
              color = "red") +
  facet_wrap(~ Gene, nrow = 8, ncol = 9) +
  theme_bw() +
  labs(
    title = "Random1-Normalized CS1 vs. CS3 Gene Expression",
    subtitle = paste0("Samples=", n_distinct(genes_cs13_rand1[["ottaID"]])),
    x = "CS1",
    y = "CS3"
  )

print(p_genes_cs13_rand1)
```

```{r genes-cs23-rand1, fig.height=10, fig.width=11, fig.cap='Random1-Normalized CS2 vs. CS3 Gene Expression'}
genes_cs23_rand1 <- train_ref_all %>%
  rownames_to_column("FileName") %>%
  group_by(ottaID) %>%
  mutate(n_codeset = n_distinct(CodeSet)) %>%
  filter(all(c("CS2", "CS3") %in% CodeSet)) %>%
  group_by(ottaID, CodeSet) %>%
  filter(n_codeset > 1, !duplicated(ottaID)) %>%
  ungroup() %>%
  pivot_longer(
    cols = where(is.double),
    names_to = "Gene",
    names_ptypes = list(Gene = factor()),
    values_to = "Value"
  ) %>%
  pivot_wider(
    id_cols = c(ottaID, Gene),
    names_from = "CodeSet",
    values_from = c("Value", "FileName")
  ) %>%
  group_by(Gene) %>%
  mutate(Rc = epiR::epi.ccc(Value_CS2, Value_CS3)[["rho.c"]][["est"]]) %>%
  ungroup() %>%
  mutate(Gene = fct_reorder(Gene, Rc, .desc = TRUE),
         Rc = paste0("Rc = ", round(Rc, digits = 3)))

p_genes_cs23_rand1 <-
  ggplot(genes_cs23_rand1, aes(x = Value_CS2, y = Value_CS3)) +
  geom_point() +
  geom_text(
    x = -24,
    y = 5,
    hjust = 0,
    vjust = 1,
    aes(label = Rc),
    check_overlap = TRUE
  ) +
  geom_abline(slope = 1,
              linetype = "dashed",
              color = "red") +
  facet_wrap(~ Gene, nrow = 8, ncol = 9) +
  theme_bw() +
  labs(
    title = "Random1-Normalized CS2 vs. CS3 Gene Expression",
    subtitle = paste0("Samples=", n_distinct(genes_cs23_rand1[["ottaID"]])),
    x = "CS2",
    y = "CS3"
  )

print(p_genes_cs23_rand1)
```

```{r genes-cs13-hkgenes, fig.height=10, fig.width=11, fig.cap='HKgenes-Normalized CS1 vs. CS3 Gene Expression'}
genes_cs13_hkgenes <-
  list(CS1 = cs1_norm, CS3 = cs3_norm) %>%
  imap(~ {
    .x %>%
      rename_all(~ gsub("^X", "", .)) %>%
      pivot_longer(where(is.double),
                   names_to = "FileName",
                   values_to = "Value") %>%
      inner_join(genes_cs13_rand1,
                 by = c("Name" = "Gene", "FileName" = paste0("FileName_", .y))) %>%
      select(Name, FileName, ottaID, Value)
  }) %>%
  reduce(inner_join,
         by = c("Name", "ottaID"),
         suffix = c("_CS1", "_CS3")) %>%
  select(ottaID, Gene = Name, everything()) %>%
  group_by(Gene) %>%
  mutate(Rc = epiR::epi.ccc(Value_CS1, Value_CS3)[["rho.c"]][["est"]]) %>%
  ungroup() %>%
  mutate(Gene = fct_reorder(Gene, Rc, .desc = TRUE),
         Rc = paste0("Rc = ", round(Rc, digits = 3)))

p_genes_cs13_hkgenes <- 
  ggplot(genes_cs13_hkgenes, aes(x = Value_CS1, y = Value_CS3)) +
  geom_point() +
  geom_text(
    x = -24,
    y = 5,
    hjust = 0,
    vjust = 1,
    aes(label = Rc),
    check_overlap = TRUE
  ) +
  geom_abline(slope = 1,
              linetype = "dashed",
              color = "red") +
  facet_wrap(~ Gene, nrow = 8, ncol = 9) +
  theme_bw() +
  labs(
    title = "HKgenes-Normalized CS1 vs. CS3 Gene Expression",
    subtitle = paste0("Samples=",
                      n_distinct(genes_cs13_hkgenes[["ottaID"]])),
    x = "CS1",
    y = "CS3"
  )

print(p_genes_cs13_hkgenes)
```

```{r genes-cs23-hkgenes, fig.height=10, fig.width=11, fig.cap='HKgenes-Normalized CS2 vs. CS3 Gene Expression'}
genes_cs23_hkgenes <-
  list(CS2 = cs2_norm, CS3 = cs3_norm) %>%
  imap(~ {
    .x %>%
      rename_all(~ gsub("^X", "", .)) %>%
      pivot_longer(where(is.double),
                   names_to = "FileName",
                   values_to = "Value") %>%
      inner_join(genes_cs23_rand1,
                 by = c("Name" = "Gene", "FileName" = paste0("FileName_", .y))) %>%
      select(Name, FileName, ottaID, Value)
  }) %>%
  reduce(inner_join,
         by = c("Name", "ottaID"),
         suffix = c("_CS2", "_CS3")) %>%
  select(ottaID, Gene = Name, everything()) %>%
  group_by(Gene) %>%
  mutate(Rc = epiR::epi.ccc(Value_CS2, Value_CS3)[["rho.c"]][["est"]]) %>%
  ungroup() %>%
  mutate(Gene = fct_reorder(Gene, Rc, .desc = TRUE),
         Rc = paste0("Rc = ", round(Rc, digits = 3)))

p_genes_cs23_hkgenes <- 
  ggplot(genes_cs23_hkgenes, aes(x = Value_CS2, y = Value_CS3)) +
  geom_point() +
  geom_text(
    x = -24,
    y = 5,
    hjust = 0,
    vjust = 1,
    aes(label = Rc),
    check_overlap = TRUE
  ) +
  geom_abline(slope = 1,
              linetype = "dashed",
              color = "red") +
  facet_wrap(~ Gene, nrow = 8, ncol = 9) +
  theme_bw() +
  labs(
    title = "HKgenes-Normalized CS2 vs. CS3 Gene Expression",
    subtitle = paste0("Samples=",
                      n_distinct(genes_cs23_hkgenes[["ottaID"]])),
    x = "CS2",
    y = "CS3"
  )

print(p_genes_cs23_hkgenes)
```
